### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by velkyel** [ralesi/helm-pt#3]
hello there,

after call (searching aaa string) helm-do-pt it fails in helm-pt--command("aaa") on error: (void-variable helm-default-directory)

and after calling helm-projectile-pt:
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  find-file-name-handler(nil file-remote-p)
  file-remote-p(nil)
  helm-process-deferred-sentinel-hook(#<process *helm pt*> "finished\n" nil)

emacs 25.0.50.2, helm-20151103.944, helm-projectile-20151021.248

**Comment by ralesi** [comment]
@velkyel , I just submitted a commit, which I believe fixes the issue.
